# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68ee563a3b52060ff0d9f8f3f56d649fef574a02cea1a3bf940eacb4823d7719be37a563466b6a752bc221ad099b5d1b5dd76cafaf96b3b3bf658b5368349f56

test:
  secret_key_base: 96bf4db7d6b8b00ae4e65951cbabd67ab4b75282398c56841f2a625974c28f3f44a83a10f460f5278f6c820fd6ac1878accc0cd6b7df42fd955f9727065e63e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
